export type ForbiddenWordEntry = {
  word: string;
  replacement: string;
  category: string;
};

export const FORBIDDEN_WORDS_DATA: ForbiddenWordEntry[] = [
  // ===== 绝对化/极限用语 =====
  { word: "最好", replacement: "非常好", category: "绝对化用语" },
  { word: "最佳", replacement: "优质", category: "绝对化用语" },
  { word: "最优", replacement: "更优", category: "绝对化用语" },
  { word: "最低价", replacement: "活动价", category: "绝对化用语" },
  { word: "最便宜", replacement: "性价比高", category: "绝对化用语" },
  { word: "最高级", replacement: "高品质", category: "绝对化用语" },
  { word: "最高端", replacement: "高端", category: "绝对化用语" },
  { word: "最先进", replacement: "先进", category: "绝对化用语" },
  { word: "最新", replacement: "全新", category: "绝对化用语" },
  { word: "最大", replacement: "超大", category: "绝对化用语" },
  { word: "最小", replacement: "迷你", category: "绝对化用语" },
  { word: "最强", replacement: "强劲", category: "绝对化用语" },
  { word: "第一", replacement: "领先", category: "绝对化用语" },
  { word: "第一名", replacement: "名列前茅", category: "绝对化用语" },
  { word: "第一品牌", replacement: "知名品牌", category: "绝对化用语" },
  { word: "唯一", replacement: "少有", category: "绝对化用语" },
  { word: "独一无二", replacement: "与众不同", category: "绝对化用语" },
  { word: "顶级", replacement: "高端", category: "绝对化用语" },
  { word: "顶尖", replacement: "优秀", category: "绝对化用语" },
  { word: "极致", replacement: "出色", category: "绝对化用语" },
  { word: "极品", replacement: "精品", category: "绝对化用语" },
  { word: "绝对", replacement: "相当", category: "绝对化用语" },
  { word: "绝无仅有", replacement: "非常稀有", category: "绝对化用语" },
  { word: "史无前例", replacement: "少见", category: "绝对化用语" },
  { word: "万能", replacement: "多功能", category: "绝对化用语" },
  { word: "100%", replacement: "高比例", category: "绝对化用语" },
  { word: "百分百", replacement: "高比例", category: "绝对化用语" },
  { word: "全网最低", replacement: "本场活动价", category: "绝对化用语" },
  { word: "全网最低价", replacement: "本场活动价", category: "绝对化用语" },
  { word: "销量第一", replacement: "热销", category: "绝对化用语" },
  { word: "行业第一", replacement: "行业领先", category: "绝对化用语" },
  { word: "NO.1", replacement: "领先", category: "绝对化用语" },
  { word: "冠军", replacement: "优胜", category: "绝对化用语" },
  { word: "王者", replacement: "佼佼者", category: "绝对化用语" },
  { word: "遥遥领先", replacement: "处于前列", category: "绝对化用语" },
  { word: "无与伦比", replacement: "出类拔萃", category: "绝对化用语" },
  { word: "前所未有", replacement: "少见", category: "绝对化用语" },
  { word: "空前绝后", replacement: "非常难得", category: "绝对化用语" },
  { word: "永久", replacement: "持久", category: "绝对化用语" },
  { word: "永远", replacement: "长期", category: "绝对化用语" },

  // ===== 虚假承诺 =====
  { word: "假一赔十", replacement: "正品保障", category: "虚假承诺" },
  { word: "假一赔百", replacement: "正品保障", category: "虚假承诺" },
  { word: "保证有效", replacement: "使用体验好", category: "虚假承诺" },
  { word: "保证见效", replacement: "用户反馈不错", category: "虚假承诺" },
  { word: "无效退款", replacement: "支持退换", category: "虚假承诺" },
  { word: "包治", replacement: "有助于改善", category: "虚假承诺" },
  { word: "包好", replacement: "有助于改善", category: "虚假承诺" },
  { word: "立竿见影", replacement: "使用感受明显", category: "虚假承诺" },
  { word: "立即见效", replacement: "体验感不错", category: "虚假承诺" },
  { word: "马上见效", replacement: "体验感不错", category: "虚假承诺" },
  { word: "一次见效", replacement: "体验感不错", category: "虚假承诺" },
  { word: "药到病除", replacement: "有助于改善", category: "虚假承诺" },
  { word: "秒杀全场", replacement: "本场优惠力度大", category: "虚假承诺" },
  { word: "抄底价", replacement: "优惠价", category: "虚假承诺" },
  { word: "跳楼价", replacement: "特惠价", category: "虚假承诺" },
  { word: "亏本卖", replacement: "让利促销", category: "虚假承诺" },
  { word: "赔本卖", replacement: "让利促销", category: "虚假承诺" },
  { word: "血亏", replacement: "大力度优惠", category: "虚假承诺" },
  { word: "清仓价", replacement: "特惠价", category: "虚假承诺" },
  { word: "出厂价", replacement: "优惠价", category: "虚假承诺" },
  { word: "成本价", replacement: "优惠价", category: "虚假承诺" },

  // ===== 医疗健康功效 =====
  { word: "治疗", replacement: "有助于改善", category: "医疗功效" },
  { word: "治愈", replacement: "有助于缓解", category: "医疗功效" },
  { word: "治病", replacement: "有助于调理", category: "医疗功效" },
  { word: "疗效", replacement: "使用感受", category: "医疗功效" },
  { word: "药效", replacement: "使用体验", category: "医疗功效" },
  { word: "根治", replacement: "有助于改善", category: "医疗功效" },
  { word: "痊愈", replacement: "好转", category: "医疗功效" },
  { word: "康复", replacement: "恢复", category: "医疗功效" },
  { word: "减肥", replacement: "体重管理", category: "医疗功效" },
  { word: "瘦身", replacement: "塑形", category: "医疗功效" },
  { word: "燃脂", replacement: "运动辅助", category: "医疗功效" },
  { word: "排毒", replacement: "促进代谢", category: "医疗功效" },
  { word: "祛痘", replacement: "改善肌肤状态", category: "医疗功效" },
  { word: "祛斑", replacement: "淡化瑕疵", category: "医疗功效" },
  { word: "美白", replacement: "提亮肤色", category: "医疗功效" },
  { word: "抗衰老", replacement: "延缓肌肤老化", category: "医疗功效" },
  { word: "抗皱", replacement: "淡化细纹", category: "医疗功效" },
  { word: "丰胸", replacement: "胸部护理", category: "医疗功效" },
  { word: "壮阳", replacement: "活力提升", category: "医疗功效" },
  { word: "补肾", replacement: "滋养调理", category: "医疗功效" },
  { word: "降血压", replacement: "辅助健康管理", category: "医疗功效" },
  { word: "降血糖", replacement: "辅助健康管理", category: "医疗功效" },
  { word: "降血脂", replacement: "辅助健康管理", category: "医疗功效" },
  { word: "防癌", replacement: "健康生活方式", category: "医疗功效" },
  { word: "抗癌", replacement: "健康生活方式", category: "医疗功效" },
  { word: "消炎", replacement: "舒缓", category: "医疗功效" },
  { word: "杀菌", replacement: "清洁", category: "医疗功效" },
  { word: "抑菌", replacement: "清洁护理", category: "医疗功效" },

  // ===== 导流违规 =====
  { word: "加微信", replacement: "关注店铺", category: "导流违规" },
  { word: "加我微信", replacement: "关注店铺", category: "导流违规" },
  { word: "微信下单", replacement: "点击购物车下单", category: "导流违规" },
  { word: "私聊下单", replacement: "点击购物车下单", category: "导流违规" },
  { word: "私信下单", replacement: "点击购物车下单", category: "导流违规" },
  { word: "加好友", replacement: "关注账号", category: "导流违规" },
  { word: "加群", replacement: "加入粉丝团", category: "导流违规" },
  { word: "淘宝", replacement: "其他平台", category: "导流违规" },
  { word: "天猫", replacement: "其他平台", category: "导流违规" },
  { word: "京东", replacement: "其他平台", category: "导流违规" },
  { word: "拼多多", replacement: "其他平台", category: "导流违规" },
  { word: "闲鱼", replacement: "其他平台", category: "导流违规" },

  // ===== 低俗/歧视 =====
  { word: "屌丝", replacement: "普通用户", category: "低俗歧视" },
  { word: "逼格", replacement: "品质感", category: "低俗歧视" },
  { word: "装逼", replacement: "有面子", category: "低俗歧视" },
  { word: "脑残", replacement: "不理智", category: "低俗歧视" },
  { word: "智障", replacement: "不合理", category: "低俗歧视" },
  { word: "穷鬼", replacement: "预算有限的朋友", category: "低俗歧视" },
  { word: "土鳖", replacement: "不了解的朋友", category: "低俗歧视" },

  // ===== 虚假营销 =====
  { word: "仅剩最后", replacement: "库存有限", category: "虚假营销" },
  { word: "最后一批", replacement: "本批次", category: "虚假营销" },
  { word: "卖完就没了", replacement: "数量有限", category: "虚假营销" },
  { word: "限量抢购", replacement: "限时优惠", category: "虚假营销" },
  { word: "手慢无", replacement: "抓紧时间", category: "虚假营销" },
  { word: "错过再等一年", replacement: "活动时间有限", category: "虚假营销" },
  { word: "史上最低", replacement: "活动力度大", category: "虚假营销" },
  { word: "全年最低", replacement: "本次活动优惠", category: "虚假营销" },
  { word: "不买后悔", replacement: "值得入手", category: "虚假营销" },
  { word: "买到就是赚到", replacement: "非常划算", category: "虚假营销" },
  { word: "过了这村没这店", replacement: "机会难得", category: "虚假营销" },
  { word: "今天不买明天涨价", replacement: "活动价格优惠", category: "虚假营销" },

  // ===== 权威性虚假宣称 =====
  { word: "国家级", replacement: "专业级", category: "虚假宣称" },
  { word: "驰名商标", replacement: "知名品牌", category: "虚假宣称" },
  { word: "中国名牌", replacement: "知名品牌", category: "虚假宣称" },
  { word: "特供", replacement: "精选", category: "虚假宣称" },
  { word: "专供", replacement: "定制", category: "虚假宣称" },
  { word: "央视推荐", replacement: "媒体关注", category: "虚假宣称" },
  { word: "明星同款", replacement: "同风格", category: "虚假宣称" },
  { word: "网红推荐", replacement: "用户喜爱", category: "虚假宣称" },
  { word: "医生推荐", replacement: "专业建议", category: "虚假宣称" },
  { word: "专家推荐", replacement: "专业认可", category: "虚假宣称" },
];
